"""empty message

Revision ID: 4ab216c2b301
Revises: 
Create Date: 2022-03-20 16:43:19.621644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab216c2b301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('secret_key', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_guid'), 'apps', ['guid'], unique=True)
    op.create_table('delayed_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'running', 'excuted', 'failed', 'cancelled'), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('backoff_delay', sa.Integer(), nullable=True),
    sa.Column('backoff_fixed', sa.Boolean(), nullable=True),
    sa.Column('lambda_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('result_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('countdown', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delayed_jobs_guid'), 'delayed_jobs', ['guid'], unique=True)
    op.create_table('recurrent_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'running', 'excuted', 'failed', 'cancelled'), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('backoff_delay', sa.Integer(), nullable=True),
    sa.Column('backoff_fixed', sa.Boolean(), nullable=True),
    sa.Column('lambda_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('result_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('cron_rule', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrent_jobs_guid'), 'recurrent_jobs', ['guid'], unique=True)
    op.create_table('regular_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'running', 'excuted', 'failed', 'cancelled'), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('backoff_delay', sa.Integer(), nullable=True),
    sa.Column('backoff_fixed', sa.Boolean(), nullable=True),
    sa.Column('lambda_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('result_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regular_jobs_guid'), 'regular_jobs', ['guid'], unique=True)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'running', 'excuted', 'failed', 'cancelled'), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('backoff_delay', sa.Integer(), nullable=True),
    sa.Column('backoff_fixed', sa.Boolean(), nullable=True),
    sa.Column('lambda_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('result_webhook_url', sa.String(length=150), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_guid'), 'scheduled_jobs', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_jobs_guid'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_regular_jobs_guid'), table_name='regular_jobs')
    op.drop_table('regular_jobs')
    op.drop_index(op.f('ix_recurrent_jobs_guid'), table_name='recurrent_jobs')
    op.drop_table('recurrent_jobs')
    op.drop_index(op.f('ix_delayed_jobs_guid'), table_name='delayed_jobs')
    op.drop_table('delayed_jobs')
    op.drop_index(op.f('ix_apps_guid'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
